### ISSUE TITLE
No IA page for Mongo shell cheat sheet

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/community-platform#1043]
This PR doesn't seem to have an IA page:
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1747

There's already a separate [MongoDB cheat sheet](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1636) in progress so maybe there was a naming conflict?

**Comment by moollaza** [comment]
@tagawa I just haven't made an IA page link yet, because I haven't gotten to the PR yet. We generate them when I add a link to the PR. In this case, seeing as it's a duplicate we won't need an IA page though.

**Comment by tagawa** [comment]
Ah, OK. I thought it was done automatically and something broke.
Closing is good, thanks.
