### ISSUE TITLE
On / Off button not translated on Settings pages

### ISSUE THREAD

**Issue by preemeijer** [duckduckgo/community-platform#1092]
Hello,

Today I saw that the on / off button is not translated the right way.
Tested it with multiple languages. It's not a big of a deal for the Dutch language cause most people will know what you need to do but... It's an issue that I want to address here.

Greetings, Paul

**Comment by jbarrett** [comment]
Thanks @preemeijer! Update for this should be out in the coming days.

**Comment by jbarrett** [comment]
This change should be live - closing.

**Comment by preemeijer** [comment]
Thank you :+1:
