### ISSUE TITLE
Change menu position of Community Leaders Spanish translation

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/community-platform#1175]
In the left-hand menu of the help pages the [Community Leaders (es)](https://duck.co/help/community/community-leaders-es) item is far above it's English equivalent ([Community Leaders](https://duck.co/help/community/community-leaders)). Ideally it should be moved one below. The section index page is fine by the way.

**Comment by jbarrett** [comment]
Thanks @tagawa!

**Comment by tagawa** [comment]
Gracias to you for the new sort thingy.
