### ISSUE TITLE
"Incorrect password" message when adding email to account

### ISSUE THREAD

**Issue by franz-mokka** [duckduckgo/community-platform#1210]
Trying to add an email address shows an "Incorrect Password" message, even though there is no password field on the form.

This happens when using GitHub to log in.

![ddg_pass](https://cloud.githubusercontent.com/assets/12204773/12768460/f5ceda38-c9cc-11e5-864a-e09e52b18753.png)

**Comment by yash14123** [comment]
I am on it.

**Comment by jbarrett** [comment]
This issue should be resolved.

**Comment by franz-mokka** [comment]
Yeah, changing email works now. Thanks.
