### ISSUE TITLE
Blog not displayed correctly in mobile

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/community-platform#1224]
![wp_ss_20160214_0002](https://cloud.githubusercontent.com/assets/8397274/13032865/91962358-d329-11e5-9e46-1c491c88d6bd.png)

Browser: Microsoft edge
Os: Windows phone 10

**Comment by gautamkrishnar** [comment]
@duckduckgo/community-leaders  any idea on this?

**Comment by jbarrett** [comment]
I believe @jagtalon is actively working on this - going to assign

**Comment by jagtalon** [comment]
@gautamkrishnar hi! This was fixed in https://github.com/duckduckgo/community-platform/pull/1233 :)
