### ISSUE TITLE
Incorrect back-end files on IA page

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/community-platform#1248]
A recent PR of mine (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2060) modified the `DateMath` Goodie, along with some other files out of necessity. The IA Page is displaying these additional files under the back-end files section:

![screenshot from 2016-02-26 21 28 23](https://cloud.githubusercontent.com/assets/8598426/13365966/1f19b7f8-dcd0-11e5-9706-babcce0eefc2.png)

![screenshot from 2016-02-26 21 30 22](https://cloud.githubusercontent.com/assets/8598426/13365977/2f2edbb4-dcd0-11e5-8910-38405f508802.png)

When it should just be `DateMath.pm` and `DateMath.t`.

*(Side note: I'm not on the contributors list)*

**Comment by MariagraziaAlastra** [comment]
Hey @GuiltyDolphin!
Thanks for spotting this, I can explain why that's the case: the code files are updated based on the files modified in the PR, and in fact: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2060/files
Seems like we need to add more checks to make sure we only add files that belong to that IA :smile:

Also, I added you to the contributors list and will give you edit permissions shortly.

/cc @jdorweiler

**Comment by GuiltyDolphin** [comment]
Thanks @MariagraziaAlastra!

Yeah - makes me wonder about the case where multiple cheat sheets (this will happen!) are updated at once? I'll let you know if I see any more IAs with erroneous files.

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra Another one with weird back-end files! https://duck.co/ia/view/cheat_sheets

Also, which data is the Controller displaying triggers for? Vim cheat sheet?

**Comment by jdorweiler** [comment]
This is where we actually determine which files are included when the PR is merged.  I'll need to add a check in here to exclude cases like this.  Although, I can't think of a good way to do this yet. 
https://github.com/duckduckgo/community-platform/blob/master/script/ghIssues.pl#L342

**Comment by GuiltyDolphin** [comment]
@jdorweiler Thanks. So does it only give the base of the file? Or does it give the whole path? The example isn't very enlightening in that regard.

**Comment by GuiltyDolphin** [comment]
@jdorweiler It looks like the current checks happen here: https://github.com/duckduckgo/community-platform/blob/888affb9e4d284936538ea5356a465b768e56fcd/src/js/ia/IAPage.js#L71

But maybe it is preferable to filter out the 'irrelevant' files before this point?

**Comment by jdorweiler** [comment]
I think it's best to keep them out of the database instead of filtering them on the front end.

**Comment by GuiltyDolphin** [comment]
@jdorweiler I agree. I'd have more of a look but... It's still building :wink: This has a lot of dependencies!

**Comment by alohaas** [comment]
Is this issue related to https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3148#issuecomment-221854439

**Comment by GuiltyDolphin** [comment]
@alohaas Looks like it!

**Comment by MariagraziaAlastra** [comment]
@GuiltyDolphin this specific issue was fixed by the data provided by more recent PRs:
![screenshot-duck co 2016-06-01 19-39-55](https://cloud.githubusercontent.com/assets/3652195/15719578/d25e3874-2830-11e6-8ed7-ef58b92283e3.png)

Also you're listed as contributor now :smile: 
Closing!
