### ISSUE TITLE
IA title casing

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/community-platform#1275]
Do you guys think this is a bug or am I just being pedantic?

![screen shot 2016-03-12 at 23 33 47](https://cloud.githubusercontent.com/assets/8960296/13725980/0dd55df8-e8ab-11e5-80ec-ebc6f13a1863.png)

I inputted **OCaml** but it is being rendered **Ocaml** in the view.

**Comment by pjhampton** [comment]
This looks rectified to me. https://duck.co/ia/view/ocaml_cheat_sheet

**Comment by tagawa** [comment]
Oh yes, I changed it in the IA page but forgot to mention it here.
Not pedantic at all @pjhampton and thanks for reporting.
