### ISSUE TITLE
Add trigger data for testing

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/community-platform#1303]
@jbarrett I was talking with @alohaas about this a bit - would it be possible to have some test data for triggering so we can interact with the graphs without breaching data we aren't supposed to have access to?

Could we either a) have a means of authing so we can get real data for IAs we can access, or b) have some randomized sets of data that show sensible triggering (i.e, high triggering for some IAs, medium for most, low for a few).

Currently I only get the `Not enough data` message.

**Comment by jbarrett** [comment]
@MariagraziaAlastra @jdorweiler I'm presuming we can build a script that just sprays noisy (not totally random, but fluctuating) numbers into the appropriate tables simply enough?

**Comment by MariagraziaAlastra** [comment]
Yeah we could populate the table with random values
