### ISSUE TITLE
Use HTTPS for Contributer Profiles

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/community-platform#1330]
We have HTTP Secure on https://duck.co, we should support it on duckduckhack.com seeing as that's where we are locating the Contributer Profiles.

/cc @alohaas @jbarrett

**Comment by jbarrett** [comment]
Cc: @jkv thanks!

**Comment by GuiltyDolphin** [comment]
@jbarrett Looks like we've got HTTPS now https://duckduckhack.com :smile:
