### ISSUE TITLE
IA Page links should point to Contributer Profiles

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/community-platform#1332]
We should have the links on the Instant Answer Pages direct to the Contributer Profiles where appropriate:

![screenshot from 2016-04-19 19 57 01](https://cloud.githubusercontent.com/assets/8598426/14651733/12999a4e-0669-11e6-8ccf-7e347887ac4d.png)

**Comment by MariagraziaAlastra** [comment]
@GuiltyDolphin Thanks, this is actually done in #1301 but we're waiting before merging and releasing it. :smile:

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra Oh, whoops! Should've checked the PRs first! Great to hear.

**Comment by alohaas** [comment]
Closing this issue because it will be resolved shortly.
