### ISSUE TITLE
Access of the site in Iran is blocked

### ISSUE THREAD

**Issue by hsafe** [duckduckgo/community-platform#1361]
Hi there 
I wonder if this is known and publicly anywhere yet or not and the main site does not have a contact us, so let me inform you that the site is no more accessible in Iran the dns records-no matter where you set is returning a fake local IP:

[hsafe@thinkt ~]$ dig duckduckgo.com

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> duckduckgo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7435
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;duckduckgo.com.			IN	A

;; ANSWER SECTION:
duckduckgo.com.		889	IN	A	10.10.34.36

;; Query time: 50 msec
;; SERVER: 216.146.35.35#53(216.146.35.35)
;; WHEN: Thu May 19 20:43:23 IRDT 2016
;; MSG SIZE  rcvd: 48

[hsafe@thinkt ~]$ dig duckduckgo.com @8.8.8.8

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> duckduckgo.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24119
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;duckduckgo.com.			IN	A

;; ANSWER SECTION:
duckduckgo.com.		889	IN	A	10.10.34.36

;; Query time: 51 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu May 19 20:43:50 IRDT 2016
;; MSG SIZE  rcvd: 48

[hsafe@thinkt ~]$ dig duckduckgo.com @4.2.2.4

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> duckduckgo.com @4.2.2.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54073
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;duckduckgo.com.			IN	A

;; ANSWER SECTION:
duckduckgo.com.		889	IN	A	10.10.34.36

;; Query time: 50 msec
;; SERVER: 4.2.2.4#53(4.2.2.4)
;; WHEN: Thu May 19 20:43:56 IRDT 2016
;; MSG SIZE  rcvd: 48

[hsafe@thinkt ~]$ dig dukduckgo.com dns

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> dukduckgo.com dns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17218
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 6

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dukduckgo.com.			IN	A

;; ANSWER SECTION:
dukduckgo.com.		3600	IN	A	172.99.89.208

;; AUTHORITY SECTION:
dukduckgo.com.		86400	IN	NS	ns3.parklogic.com.
dukduckgo.com.		86400	IN	NS	ns1.parklogic.com.
dukduckgo.com.		86400	IN	NS	ns4.parklogic.com.
dukduckgo.com.		86400	IN	NS	ns5.parklogic.com.
dukduckgo.com.		86400	IN	NS	ns2.parklogic.com.

;; ADDITIONAL SECTION:
ns1.parklogic.com.	151809	IN	A	69.39.239.55
ns2.parklogic.com.	151809	IN	A	69.39.239.56
ns3.parklogic.com.	151809	IN	A	173.255.218.70
ns4.parklogic.com.	70574	IN	A	178.79.134.133
ns5.parklogic.com.	70574	IN	A	106.186.126.56

;; Query time: 422 msec
;; SERVER: 198.101.242.72#53(198.101.242.72)
;; WHEN: Thu May 19 20:54:07 IRDT 2016
;; MSG SIZE  rcvd: 238

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52759
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns.				IN	A

;; AUTHORITY SECTION:
.			9482	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016051900 1800 900 604800 86400

;; Query time: 354 msec
;; SERVER: 198.101.242.72#53(198.101.242.72)
;; WHEN: Thu May 19 20:54:09 IRDT 2016
;; MSG SIZE  rcvd: 107

These are all results

**Comment by moollaza** [comment]
Hi @hsafe thanks for reporting. We have heard this news from others as well. I do not know if we plan to take any actions regarding this or whether we even can.

If there are any updates we will likely announced them on our Blog or through our newsletter.

Thanks again
