### ISSUE TITLE
Contributor Profiles: Some IAs duplicated in 'Issues & PRs'

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/community-platform#1370]
For example:

![screenshot-2016-05-24-13 51 27_756_543](https://cloud.githubusercontent.com/assets/8598426/15504416/cb73c108-21b6-11e6-98f8-33464964c944.png)

/cc @alohaas

**Comment by alohaas** [comment]
@GuiltyDolphin I believe this has been fixed. See https://github.com/duckduckgo/community-platform/pull/1373

**Comment by GuiltyDolphin** [comment]
@alohaas Thanks! I think we need more linking :wink:
