### ISSUE TITLE
Contributor Profiles: Some PRs being incorrectly assigned

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/community-platform#1371]
In https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3135 I have linked to the Shuffle IA Page (as it is the main link to point people to for IAs):

![screenshot-2016-05-24-13 55 10_682_87](https://cloud.githubusercontent.com/assets/8598426/15504589/99789704-21b7-11e6-8124-1c2101020338.png)

And then on the Contributor Profile it has linked that issue to the IA, even though the PR does not directly concern the IA:

![screenshot-2016-05-24-13 54 41_799_163](https://cloud.githubusercontent.com/assets/8598426/15504612/b60857e2-21b7-11e6-95a7-765326e901ba.png)

/cc @alohaas

**Comment by alohaas** [comment]
@jagtalon @MariagraziaAlastra Ideally, this would not be happening. Is there a way to distinguish between an intentional and an unintentional link to an IA Page?

**Comment by GuiltyDolphin** [comment]
@alohaas In general people should be using a format similar to `IA Page: https://duck.co/ia/view/...` near the foot of the description - maybe we could check for that (or to make sure it appears after the last `---`)?

**Comment by MariagraziaAlastra** [comment]
Yeah but people don't always use IA Page: etc, sometimes there's just the link and we want to have a pretty good coverage of all issues and PRs for each IA :\
@jdorweiler any ideas here?

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra Well, we've got an [issue template](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2949) in progress, and people do seem to be using the `Create Issue` button a lot more now - so maybe that could help?

I wouldn't be averse to really pushing the use of the IA pages to create issues, it allows a lot more automation; perhaps more 'warnings' (other repos have things like "DO NOT create an issue here (bla bla)" - usually have a separate bug tracker though)?

**Comment by jdorweiler** [comment]
What about just taking the last IA page linked in the post? That could work without forcing people to follow any new rules.

Relevant code is here if anyone want to try fixing it. 
https://github.com/duckduckgo/community-platform/blob/master/script/ghIssues.pl#L84

**Comment by GuiltyDolphin** [comment]
@jdorweiler Hmm, unfortunately some PRs legitimately modify multiple IAs so each would want updating. 

I don't see anything wrong with standardizing the format (e.g., `IA Page: https://duck.co/ia/view/...`); it's probably something we'll want to do in the future anyway.

We're supposed to be using a standard format for titles as well (e.g., `DateMath: Add cheese and socks`) so perhaps we could use that too?

**Comment by jdorweiler** [comment]
Good point.  A standard format sounds good to me.

**Comment by GuiltyDolphin** [comment]
@jdorweiler I'll PR a quickie then.
