### ISSUE TITLE
IA Page: unrelated front-end files listed on IA page

### ISSUE THREAD

**Issue by alohaas** [duckduckgo/community-platform#1376]
See https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3148 for detailed information and screenshot of issue.

@MariagraziaAlastra @jagtalon any ideas?

**Comment by MariagraziaAlastra** [comment]
Probably got in there after a PR containing changes to multiple IAs was merged. There isn't an easy way to prevent this from happening, so we need to fix the data using sql.
It would be cool if the list of code files could be editable, too.

**Comment by alohaas** [comment]
Ahhhhhhh @MariagraziaAlastra that's not very good.
I think making that list editable would be a useful feature

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra @alohaas Is this the same as https://github.com/duckduckgo/community-platform/issues/1248 ?

**Comment by MariagraziaAlastra** [comment]
Same issue yeah

**Comment by MariagraziaAlastra** [comment]
Solved by #1383
