### ISSUE TITLE
Switching IA type changes PR links

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/community-platform#1485]
**This is low priority as it's an edge case.**

The Interactive Calculator was in the process of being developed as a Spice two years ago due to API reasons. Now it needs to be ported to a Goodie. I was in the process of investigating this and marked the old issue with the IA page. I then switched the IA type from Spice => Goodie and this changed the link. See the attached screenshots.

**Screenshot 1: Spice**
![screen shot 2017-03-16 at 3 52 08 pm](https://cloud.githubusercontent.com/assets/8960296/24005433/e7867c8a-0a60-11e7-80d4-8475c855f00c.png)

**Screenshot 2: Goodie**
![screen shot 2017-03-16 at 3 52 29 pm](https://cloud.githubusercontent.com/assets/8960296/24005436/ea05a760-0a60-11e7-9860-4bab70569224.png)

**Comment by levthedev** [comment]
I just ran into this issue on the Geometry IA - I was just about to file an issue when I saw this. 

Just thought I'd leave this here so that if anyone goes back and is looking for others that have been changed, they won't miss Geometry.
