### ISSUE TITLE
Fix external links and embedded images on duck.co / DDH docs.

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/community-platform#302]
It seems I was a little over-zealous in new measures to anonymise content on the platform and external links / embedded images are breaking for various reasons.

@moollaza added the DDG image proxy to stuff in the DDH docs, but the docs presentation code does HTML entity-ising so these are still broken - can we mark texts as raw in the docs? The image url also needs to be urlencoded.

I'm trying to solve the external link redirect thing, but my js-fu is weak, so will probably need some help.

cc @zekiel @russellholt @MariagraziaAlastra @jagtalon @jdorweiler

**Comment by jbarrett** [comment]
@moollaza I think this is no longer an issue, so closing for now

**Comment by moollaza** [comment]
:+1:
