### ISSUE TITLE
We need a new help system that is also a bit more bound to the translation concept

### ISSUE THREAD

**Issue by Getty** [duckduckgo/community-platform#32]

**Comment by javathunderman** [comment]
@zekiel Can this be closed?

**Comment by zekiel** [comment]
@javathunderman  ya, help_overhaul would be its own project as well as making the help pages translatable. As mentioned, tokenizing duck.co so it can be translated is on the to-do list. When it becomes more relevant, we'll probably make a milestone for it like we have now.
