### ISSUE TITLE
Feedback icon font 404

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/community-platform#426]
Not sure what changed, but it looks like the icon fonts for the feedback pages has gone AWOL:

![Feedback - missing icons](http://jbrt.org/ddg/feedback.png)

Checked so far:
- nginx, serving ddgc_static correctly
- feedback.css changes - none recently in this area.

Not sure when this was introduced.

cc @malbin @jdorweiler @sdougbrown @zekiel Thanks!

**Comment by javathunderman** [comment]
@jbarrett Should this be closed?

**Comment by zekiel** [comment]
believe so based on #440  and testing
