### ISSUE TITLE
Malformed Links

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/community-platform#427]
When using the "Add A Link" feature, the resultant link is malformed as it includes "href". For example, **[url href=http://ddg.gg]** should be **[url=http://ddg.gg]**

**Comment by zekiel** [comment]
dang--when did that pop up?

**Comment by x-15a2** [comment]
Well, I truly believe that I had an issue with this, but I just tested again and was unable to replicate it. Sorry for the bad report, probably too much eggnog!

**Comment by jbarrett** [comment]
Not a problem, @x-15a2 - would rather get the occasional erroneous report than miss out on finding out about a bug :)
