### ISSUE TITLE
No delete button for general ramblings. 

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/community-platform#436]
Meant for ComLeaders.

cc @zekiel

**Comment by zekiel** [comment]
I think the volume makes it hard to handle. Since you're forced to mix potentially good posts that will be approved with ones you're trying to delete.

**Comment by javathunderman** [comment]
@zekiel @jbarrett Yeah, it's a little overwhelming at times.

**Comment by jbarrett** [comment]
This is where presentation of the button is handled in the templates - could add `forum_manager` to the conditional:

https://github.com/duckduckgo/community-platform/blob/d47cde1/templates/i/comment/thread.tx#L49-L52

and the check here should be changed too:

https://github.com/duckduckgo/community-platform/blob/d47cde1/lib/DDGC/Web/Controller/Forum/My.pm#L83-L86

@zekiel Happy to do this?

**Comment by zekiel** [comment]
sounds good to me

**Comment by jbarrett** [comment]
@zekiel @javathunderman This should be working on live.

**Comment by javathunderman** [comment]
Good to know. I will be cleaning some stuff up.

**Comment by jbarrett** [comment]
Thanks @javathunderman. Closing this.
