### ISSUE TITLE
Link redirecting improperly 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/community-platform#446]
https://duck.co/blog/instant-answers-and-the-back-button 

the "people in space" link is improperly redirecting to a search for "who" on duckduckgo. Maybe an encoding issue? 

// @jbarrett

**Comment by jbarrett** [comment]
Weird, if you click this (which will have the wrong referer and send you through the interstitial redirect page) the link is correct. Looking into it now.

https://duck.co/redir/?u=https%3A%2F%2Fduckduckgo.com%2F%3Fq%3Dwho%2527s%2Bin%2Bspace%2Bright%2Bnow

**Comment by jbarrett** [comment]
Oh, no, that's broken too. HTML entities being introduced, think I need to mark that variable as raw.

**Comment by jbarrett** [comment]
Sorry, this took a ridiculous amount of time to go live, but should now be resolved (for this blog post at least) :)
