### ISSUE TITLE
token notes can't be saved by Translation Managers 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/community-platform#486]
The function exists to edit and save the notes, but it only reloads the page. 

//cc @jbarrett  i think this is a pernicious pita and i'm sorry to deliver only sadness to your notification inbox http://i.imgur.com/7wxNAH2.gif

**Comment by jbarrett** [comment]
Is this only in the "Browse Tokens" view? I can add notes from the translation view.

**Comment by jbarrett** [comment]
In browse view, the notes can't be amended by anyone :rage4:

**Comment by jbarrett** [comment]
A fix for this went live today which should fix adding token notes from all views.

**Comment by preemeijer** [comment]
Thanks John ^_^
