### ISSUE TITLE
Fast translation wizard?

### ISSUE THREAD

**Issue by jwalantsoneji** [duckduckgo/community-platform#497]
The current wizard lets one item to be translated at a time. Clicking next, waiting for page load takes lot of time.
Can we have a wizard which can let multiple strings to be translated in one page?

**Comment by jbarrett** [comment]
If you go to the browse view, you can set the number of tokens to load per page and submit multiple translations at once.

Translate -> Domain -> Language -> Browse

Thanks!

**Comment by jwalantsoneji** [comment]
Thanks... works great!
