### ISSUE TITLE
IA metadata - database [question]

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/community-platform#645]
Maybe someone in the community can point me in the right direction, I'd love to be able to manipulate the IA pages locally.

I'm having an issue importing the IA metadata using [iameta.pl](https://github.com/duckduckgo/community-platform/blob/dev/script/iameta.pl)

**The steps I took:**

`$ curl https://duck.co/ia/json -o "/home/<username>/ddgc/cache/all_meta.json"`

`$ ./script/iameta.pl`

Result (error.log): (TL;DR **ERROR:  null value in column "code_review" violates not-null constraint**
```bash
Error updating iameta, Rolling back update: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  null value in column "code_review" violates not-null constraint [for Statement "INSERT INTO "instant_answer" ( "description", "dev_milestone", "id", "meta_id", "name", "repo", "src_name", "template") VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )" with ParamValues: 1='24', 2='live', 3='24', 4='24', 5='24', 6='fathead', 7='24 Wiki', 8=undef]
```

**Proof the database is setup and working**

`ddgc=# \dt`
````bash
                    List of relations
 Schema |              Name               | Type  | Owner 
--------+---------------------------------+-------+-------
 public | instant_answer                  | table | ddg
 public | instant_answer_blocks           | table | ddg
 public | instant_answer_issues           | table | ddg
 public | instant_answer_topics           | table | ddg
 public | instant_answer_updates          | table | ddg
 public | instant_answer_users            | table | ddg
````

`ddgc=# select * from instant_answer;`
````bash
id | meta_id | name | description | answerbar | perl_module | perl_dependencies | dev_milestone | is_live | milestone_dates | status | repo | topic | code | src_name | src_url | src_api_documentation | api_status_page | icon_url | screenshot | mockups | template_group | custom_templates | triggers | example_query | other_queries | signal_from | tab | attribution_orig | template | attribution | screenshots | unsafe | type | producer | designer | developer | code_review | design_review | test_machine | browsers_ie | browsers_chrome | browsers_firefox | browsers_safari | browsers_opera | mobile_android | mobile_ios | tested_relevancy | tested_staging | src_options | src_id | src_domain 
````

It's possible the data I'm pulling from the endpoint `https://duck.co/ia/json` isn't the correctly formated `all_meta.json`file  thus it doesn't insert correctly, however no such file is contained in any repo? 

//CC @russellholt @jdorweiler

**Comment by russellholt** [comment]
@MrChrisW 

It's cool that you want to play with this.

This is all still under active development internally and much of it isn't ready for the community to take an active role in. It will be, but between now and then, a whole lot is going to change. Which doesn't rule out involvement, it just makes it harder.

In this case, the iameta.pl script was a one-off designed to seed the database from a relatively complex dump of all the IA data as seen internally to duckduckgo, and it has a somewhat different set and format than what the json endpoints deliver. So the output of /ia/json is unlikely to match iameta.pl's requirements. iameta.pl will probably be removed in the near future, but we really should have an importer for what we can get via the json endpoints, but we don't yet, as they likely will change quite a bit, too.

However, there is some older-ish data from the last big dump you can play with, it's just a month or so old.

modify your curl statement to get http://duckduckgo.com/metadata115.json  and it ought to work, but the database has changed a bit since then also.

let me know

**Comment by MrChrisW** [comment]
Hi @russellholt 

Thanks for the response. 

>This is all still under active development internally and much of it isn't ready for the community to take an active role in. It will be, but between now and then, a whole lot is going to change. Which doesn't rule out involvement, it just makes it harder.

Totally understand, I'm just looking to have a quick poke around the IA pages at this stage :wink: I gathered from your email that the project is still under **heavy development.** 

>In this case, the iameta.pl script was a one-off designed to seed the database from a relatively complex dump of all the IA data as seen internally to duckduckgo, and it has a somewhat different set and format than what the json endpoints deliver. So the output of /ia/json is unlikely to match iameta.pl's requirements. iameta.pl will probably be removed in the near future, but we really should have an importer for what we can get via the json endpoints, but we don't yet, as they likely will change quite a bit, too.

Thanks for clarifying. I assumed the iameta.pl script was just an initial script to propagate the db, however I did expect to see the meta `json` file contained somewhere :smile: Understand the endpoint formats change and that makes it difficult to provide an import script, I'm still once the dust settles that can be addressed :+1: 

>However, there is some older-ish data from the last big dump you can play with, it's just a month or so old.

Thanks for providing the link! I knew the data would be somewhere.

I've tried the import again however it still fails due to the existence of `meta_id` column in the db however no `meta_id` field contained in the JSON, therefore it tries to insert a null value and fails :cry: 

I'll probably just end up manually inserting some dummy values directly into the db. 

Thanks

**Comment by russellholt** [comment]
cool, no worries - and yeah.. the system has left poor iameta.pl behind. but anything that is actually missing you could probably add for the purposes of getting something working, right here
https://github.com/duckduckgo/community-platform/blob/dev/script/iameta.pl#L88

eg `$ia->{meta_id} = $ia->{id}`

good luck :)

**Comment by MrChrisW** [comment]
:+1: Thanks for your help @russellholt Imported!

```
ddgc=# select pg_size_pretty(pg_total_relation_size('instant_answer'));
 pg_size_pretty 
----------------
 328 kB
(1 row)
```
