### ISSUE TITLE
add "Develop" to header menu and link it to docs

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/community-platform#654]
https://duck.co/duckduckhack/ddh-intro 

I would find that link useful and it will help when IA pages are fully utilized.

**Comment by zekiel** [comment]
@jbarrett  think it'll fit? :)

**Comment by jbarrett** [comment]
I think we can squeeze it in there - there are some alignment changes needed and I'm not quite sure where the "pressed" effect is handled. There's css in this repo (in css files and in perl files...) and in DDGC::Static (Should they all be in this?). Also, inline in templates. Probably elsewhere.

Probably a good time to talk about this.

**Comment by jbarrett** [comment]
Opened https://github.com/duckduckgo/community-platform-static/issues/3 for discussion

**Comment by zekiel** [comment]
@jbarrett  can you please update this? If we can't squeeze it in the header, I would be ok with replacing Translate until we can.
