### ISSUE TITLE
Eastern european charset fails in some fonts

### ISSUE THREAD

**Issue by max258** [duckduckgo/community-platform#666]
For example on home screen is the text not correct, see the attached image.
![untitled-1](https://cloud.githubusercontent.com/assets/537310/7471051/a502d428-f322-11e4-848e-afc0591a714d.png)

**Comment by jbarrett** [comment]
Thanks for repoting, @max258 

Could you list which OS, Browser (and versions) you are using? Also, do you have script or ad blocking enabled? Thanks.

**Comment by max258** [comment]
W7, chrome browser 42.0.2311.135
No script or ad blocker.

I think this problem is on font side, becouse other software has same issue.
Solving can be replace font with eastern european font.

**Comment by jbarrett** [comment]
@max258 I believe this should be resolved now. Can you confirm? Thanks.

**Comment by max258** [comment]
@jbarrett Yes, solved now. Thanks
