### ISSUE TITLE
i.duck.co SSL

### ISSUE THREAD

**Issue by vojiz** [duckduckgo/community-platform#719]
![*.duck.co SSL](https://cloud.githubusercontent.com/assets/9707814/7974752/f1bde140-0a65-11e5-9334-ebd0dd5b464c.png)

SSL cert for *.duckduckgo.com domain is also attached to *.i.duck.co subdomain instead the one that was issued for *.duck.co domain.

**Comment by jbarrett** [comment]
Thanks @vojiz. I'm not sure this domain is used for anything - we should probably remove the NS entry or make it redirect properly to ddg.

**Comment by jbarrett** [comment]
Subdomain has been deprecated and removed - thanks for reporting.

**Comment by vojiz** [comment]
You are welcome.
