### ISSUE TITLE
IA Ideas Page: Votes column flushed left

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/community-platform#837]
Recently found out that the IA Ideas page looks a little different – the votes column are flushed left instead of right.  Is this intentional or a bug?  The General Ramblings look the same though.

![screen shot 2015-07-23 at 3 11 37 pm](https://cloud.githubusercontent.com/assets/5793364/8844961/3cfc9828-314d-11e5-8782-e86984d52497.png)

**Comment by jbarrett** [comment]
Thanks @altern8tif - this is definitely not intentional - we are working on it now.

**Comment by jbarrett** [comment]
Thanks for reporting this @altern8tif!

Should be resolved now.
