### ISSUE TITLE
Using status ="Not an Instant Answer Idea" doesn't migrate to Gen Ramblings 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/community-platform#868]
x.15a2 discovered that moving an Idea into "Not an Instant Answer Idea" no longer migrates the idea to a Gen Ramblings post. 

//cc @MariagraziaAlastra  @moollaza  @jagtalon

**Comment by zekiel** [comment]
//cc @jbarrett

**Comment by jbarrett** [comment]
Should be resolved, reopen if not.
