### ISSUE TITLE
No option to create an idea and assign it myself

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/community-platform#910]
I can create an idea, but the current code doesn't allow me to claim that idea myself.

**Comment by gautamkrishnar** [comment]
Cc:  @jbarrett @MariagraziaAlastra @moollaza @jagtalon

**Comment by MariagraziaAlastra** [comment]
Hey @gautamkrishnar, that's because we need to approve it first, and assign it either the "needs a developer" tag or the "quack and hack" tag!

**Comment by gautamkrishnar** [comment]
@MariagraziaAlastra Thanks :smile:

**Comment by gautamkrishnar** [comment]
@MariagraziaAlastra It would be better if it has an option (a checkbox) to assign the idea to myself. So that it will automatically claimed to my account as soon as it is approved!

**Comment by MariagraziaAlastra** [comment]
@gautamkrishnar Yeah, we were thinking of doing something like that :)
Thanks a lot for the suggestion!
