### ISSUE TITLE
Unclaimed ideas filter should include "Needs a developer"

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/community-platform#915]
https://duck.co/ideas/unclaimed

**Comment by jbarrett** [comment]
We changed this for the QnH, it should be reverted on the next release.

**Comment by tagawa** [comment]
Great, thank you.

**Comment by MariagraziaAlastra** [comment]
@tagawa The new release is out, everything is back to normal: https://duck.co/ideas/claimed

**Comment by tagawa** [comment]
Thanks - looks perfect :-)
