### ISSUE TITLE
Claiming an idea should change the status to "In development"

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/community-platform#916]
At the moment this doesn't seem to happen when the status is "Needs a developer".

**Comment by russellholt** [comment]
In the future, I think we want to engage the developer more before we get to development. In development should mean decisions have been made, like most of the stuff that the developer fills out on the PR template should be discussed and decided as much as possible before it gets to development.

There's a lot of overlap I think between them and it depends on the situation, so I expect a small number of circumstances to trigger some automatic change. The arrival of a PR for an IA that was previously in planning, for example, is one that should.

**Comment by tagawa** [comment]
Thanks for the explanation @russellholt - now makes sense that it's not something that can easily be automated. Closing this.
